# Default values for steadybit-extension-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  # image.name -- The container image to use for the Steadybit loadtest extension.
  name: ghcr.io/steadybit/extension-loadtest
  # image.tag -- tag name of the extension-loadtest container image to use. Defaults to appVersion of this chart.
  # See https://github.com/steadybit/extension-loadtest/pkgs/container/extension-loadtest/versions for all tags.
  tag: null
  # image.pullPolicy -- Specifies when to pull the image container.
  pullPolicy: Always

loadtest:
  replicaCount: 1
  servicesEnabled: "false"
  servicePortFrom: 9000
  servicePortTo: 9002
  clusterName: "cluster-loadtest"
  ec2NodeCount: 400
  gcpNodeCount: 1
  azureNodeCount: 1
  deploymentsPerNode: 5
  podsPerDeployment: 4
  containerPerPod: 2
  disableAWSDiscovery: "false"
  disableGCPDiscovery: "false"
  disableAzureDiscovery: "false"
  disableKubernetesDiscovery: "false"
  disableHostDiscovery: "false"
  disableContainerDiscovery: "false"
  discoveryDelayInMs: 0
  eventListenerEnabled: "true"
  attributeUpdates:
    - type: "com.steadybit.extension_aws.ec2-instance"
      attributeName: "aws-ec2.label.change-ts"
      rate: 0.05
      interval: 600
    - type: "com.steadybit.extension_container.container"
      attributeName: "container.label.change-ts"
      rate: 0.05
      interval: 180
    - type: "com.steadybit.extension_kubernetes.kubernetes-container"
      attributeName: "k8s.label.change-ts"
      rate: 0.05
      interval: 180
    - type: "com.steadybit.extension_kubernetes.kubernetes-deployment"
      attributeName: "k8s.label.change-ts"
      rate: 0.05
      interval: 180
  targetReplacements:
    - type: "com.steadybit.extension_aws.ec2-instance"
      count: 1
      interval: 600
    - type: "com.steadybit.extension_container.container"
      count: 2
      interval: 180
    - type: "com.steadybit.extension_kubernetes.kubernetes-container"
      count: 2
      interval: 180
    - type: "com.steadybit.extension_kubernetes.kubernetes-deployment"
      count: 2
      interval: 180


tls:
  server:
    certificate:
      # tls.server.certificate.fromSecret -- The name of the secret containing the TLS certificate for the extension.
      #  The extension will then create an HTTPS server instead of an HTTP server.
      fromSecret: null
      # tls.server.certificate.path --Path to the TLS certificate for the extension.
      path: null
      key:
        # tls.server.certificate.key-path --Path to the key for the TLS certificate for the extension.
        path: null
  client:
    certificates:
      # tls.client.certificates.fromSecrets -- List of secret names containing TLS certificates for the extension to trust.
      #  The extension will require clients to authenticate using one of these certificates. In essence, this will enable mutual TLS.
      fromSecrets: []
      # tls.client.certificates.paths -- List paths containing TLS certificates for the extension to trust.
      #  The extension will require clients to authenticate using one of these certificates. In essence, this will enable mutual TLS.
      paths: []

logging:
  # logging.level -- The active log level. Valid values are: TRACE, DEBUG, INFO, WARN, ERROR
  level: INFO
  # logging.format -- The format of the log entries. One of text, json
  format: text

probes:
  # probes.readiness.* -- Configuration of the Kubernetes readiness probe
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
  # probes.liveness.* -- Configuration of the Kubernetes liveness probe
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5
    successThreshold: 1

resources:
  requests:
    # resources.requests.memory -- The minimal amount of memory needed
    memory: "32Mi"
    # resources.requests.cpu -- The minimal amount of cpu shares needed
    cpu: "50m"
  limits:
    # resources.limits.memory -- The limit of memory to be used
    memory: "512Mi"
    # resources.limits.cpu -- The limit of cpu share to be used during its interval
    cpu: "200m"

serviceAccount:
  # serviceAccount.create -- Specifies whether a ServiceAccount should be created.
  create: true
  # serviceAccount.name -- The name of the ServiceAccount to use.
  name: steadybit-extension-loadtest

updateStrategy:
  # updateStrategy.type -- Which type of `updateStrategy` should be used.
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

# extra labels to apply to the Kubernetes resources
extraLabels: {}

# podAnnotations -- Additional annotations to be added to the pods.
podAnnotations: {}

# podLabels -- Additional labels to be added to the pods.
podLabels: {}

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}

# tolerations -- Tolerations to influence pod assignment
tolerations: []

# topologySpreadConstraints -- Spread constraints to influence pod assignment.
# https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/
topologySpreadConstraints: []

# affinity -- Affinities to influence pod assignment.
affinity: {}

# priorityClassName -- Priority class used to influence pod scheduling priority.
priorityClassName: null

# podSecurityContext -- SecurityContext to apply to the pod.
podSecurityContext: {}

# extraEnv -- Array with extra environment variables to add to the container
# e.g:
# extraEnv:
#   - name: FOO
#     value: "bar"
extraEnv: []

# extraEnvFrom -- Array with extra environment variables sources to add to the container
# e.g:
# extraEnvFrom:
#  - configMapRef:
#    name: env-configmap
#  - secretRef:
#    name: env-secrets
extraEnvFrom: []

discovery:
  attributes:
    excludes:
      # discovery.attributes.excludes.container -- List of attributes to exclude from container discovery.
      container: []
      # discovery.attributes.excludes.ec2 -- List of attributes to exclude from ec2 discovery.
      ec2: []
      # discovery.attributes.excludes.host -- List of attributes to exclude from host discovery.
      host: []
      kubernetes:
        # discovery.attributes.excludes.kubernetes.container -- List of attributes to exclude from kubernetes container discovery.
        container: []
        # discovery.attributes.excludes.kubernetes.deployment -- List of attributes to exclude from kubernetes container discovery.
        deployment: []
