apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "extensionlib.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
  {{- include "extensionlib.labels" (list .) | nindent 4 }}
spec:
  replicas: {{ .Values.loadtest.replicaCount }}
  selector:
    matchLabels:
      {{- include "extensionlib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "extensionlib.selectorLabels" . | nindent 8 }}
        {{- include "extensionlib.labels" (list .) | nindent 8 }}
        {{- range $key, $value := .Values.extraLabels }}
        {{ $key }}: {{ $value }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        oneagent.dynatrace.com/injection: "false"
        {{- include "extensionlib.annotation" (list . 8082 (list "ACTION" "DISCOVERY" "EVENT") ) | nindent 8 }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: extension
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            {{- include "extensionlib.deployment.env" (list .) | nindent 12 }}
            {{ if .Values.loadtest.clusterName -}}
            - name: STEADYBIT_EXTENSION_CLUSTER_NAME
              value: {{ .Values.loadtest.clusterName }}
            {{ end }}
            {{ if .Values.loadtest.containerPerPod -}}
            - name: STEADYBIT_EXTENSION_CONTAINER_PER_POD
              value: "{{ .Values.loadtest.containerPerPod }}"
            {{ end }}
            {{ if .Values.loadtest.deploymentsPerNode -}}
            - name: STEADYBIT_EXTENSION_DEPLOYMENTS_PER_NODE
              value: "{{ .Values.loadtest.deploymentsPerNode }}"
            {{ end }}
            {{ if .Values.loadtest.ec2NodeCount -}}
            - name: STEADYBIT_EXTENSION_EC2_NODE_COUNT
              value: "{{ .Values.loadtest.ec2NodeCount }}"
            {{ end }}
            {{ if .Values.loadtest.gcpNodeCount -}}
            - name: STEADYBIT_EXTENSION_GCP_NODE_COUNT
              value: "{{ .Values.loadtest.gcpNodeCount }}"
            {{ end }}
            {{ if .Values.loadtest.azureNodeCount -}}
            - name: STEADYBIT_EXTENSION_AZURE_NODE_COUNT
              value: "{{ .Values.loadtest.azureNodeCount }}"
            {{ end }}
            {{ if .Values.loadtest.podsPerDeployment -}}
            - name: STEADYBIT_EXTENSION_PODS_PER_DEPLOYMENT
              value: "{{ .Values.loadtest.podsPerDeployment }}"
            {{ end }}
            {{- with .Values.extraEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            {{ if .Values.loadtest.attributeUpdates -}}
            - name: STEADYBIT_EXTENSION_ATTRIBUTE_UPDATES
              value: {{ .Values.loadtest.attributeUpdates | toJson | quote }}
            {{ end }}
            {{ if .Values.discovery.attributes.excludes.container -}}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_CONTAINER
              value: {{ join "," .Values.discovery.attributes.excludes.container | quote }}
            {{ end }}
            {{ if .Values.discovery.attributes.excludes.ec2 -}}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_EC2
              value: {{ join "," .Values.discovery.attributes.excludes.ec2 | quote }}
            {{ end }}
            {{ if .Values.discovery.attributes.excludes.host -}}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_HOST
              value: {{ join "," .Values.discovery.attributes.excludes.host | quote }}
            {{ end }}
            {{ if .Values.discovery.attributes.excludes.kubernetes.container -}}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_KUBERNETES_CONTAINER
              value: {{ join "," .Values.discovery.attributes.excludes.kubernetes.container | quote }}
            {{ end }}
            {{ if .Values.discovery.attributes.excludes.kubernetes.deployment -}}
            - name: STEADYBIT_EXTENSION_DISCOVERY_ATTRIBUTES_EXCLUDES_KUBERNETES_DEPLOYMENT
              value: {{ join "," .Values.discovery.attributes.excludes.kubernetes.deployment | quote }}
            {{ end }}
            - name: STEADYBIT_EXTENSION_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "extensionlib.deployment.volumeMounts" (list .) | nindent 12 }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.liveness.successThreshold }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
            httpGet:
              path: /health/liveness
              port: 8083
          readinessProbe:
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            successThreshold: {{ .Values.probes.readiness.successThreshold }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
            httpGet:
              path: /health/readiness
              port: 8083
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
            runAsGroup: 10000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      volumes:
        {{- include "extensionlib.deployment.volumes" (list .) | nindent 8 }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- toYaml . | nindent 8 }}
      {{- end }}
