{{- if eq .Values.loadtest.servicesEnabled "true"}}
{{- range untilStep (.Values.loadtest.servicePortFrom | int) (add .Values.loadtest.servicePortTo 1 | int)  1 }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: steadybit-extension-loadtest-{{ . }}
    meta.helm.sh/release-namespace: steadybit-agent
    steadybit.com/extension-auto-discovery: |
      {"extensions":[{"port":{{ . }},"protocol":"http","types":["ACTION","DISCOVERY","EVENT"]}]}
  name: steadybit-extension-loadtest-{{ . }}
  namespace: steadybit-agent
spec:
  ports:
    - port: {{ . }}
      protocol: TCP
      targetPort: 8082
  selector:
      {{- include "extensionlib.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
