name: test

on:
  push:
    branches:
      - 'main'

jobs:
  test-build-breaker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#      - name: SonarCloud Quality Gate check
#        if: ${{ startsWith(github.ref, 'refs/tags/') && env.sonar_available == 'true' }}
#        uses: sonarsource/sonarqube-quality-gate-action@v1.1.0
#        # Force to fail step after specific time.
#        timeout-minutes: 5
#        env:
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test-2:
    runs-on: ubuntu-latest
    needs: test-build-breaker
    steps:
      - name: Piep
        run: echo piep
